version: "3"
services:
  mirai:
    build: ./mirai
    container_name: mirai
    restart: always
    ports: 
      - 8081:8080
    volumes: 
      - ./mirai/config.txt:/app/config.txt
      - ./mirai/setting.yml:/app/plugins/MiraiAPIHTTP/setting.yml
      - ./mirai/data:/app/data
      - ./mirai/images:/app/plugins/MiraiAPIHTTP/images
  bot:
    build: ./bot/deploy
    container_name: mirai_bot
    restart: always
    depends_on: 
      - mirai
    environment: 
      - API_HOST=mirai
      - API_PORT=8080
      - IMAGE_PATH=/app/images
      - DATA_STORAGE_PATH=/app/data
      - API_AUTH_KEY=1234567890
    volumes: 
      - ./mirai/images:/app/images