version: "3"
services:
  mirai:
    build: ./mirai
    container_name: mirai
    restart: always
    ports:
      - 8081:8080
    volumes:
      - ./mirai/config.txt:/app/config.txt
      - ./mirai/setting.yml:/app/plugins/MiraiAPIHTTP/setting.yml
      - ./data/mirai_data:/app/data
      - ./data/mirai_image:/app/plugins/MiraiAPIHTTP/images
  bot:
    build: ./bot/deploy
    container_name: mirai_bot
    restart: always
    depends_on:
      - mirai
      - redis
    volumes:
      - ./data/mirai_image:/app/images
      - ./data/bot_data:/app/data
  redis:
    image: redis
    container_name: redis
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf